- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: install/uninstall packages
      ansible.builtin.package:
        name: "{{item}}" # item is a default keyword
        state: present
      loop:
      - {name: 'git', state: 'present'}
      - {name: 'mysql', state: 'absent'}
      
